name = "TaskBasedProduction"
uuid = "0c6611b4-5dad-443c-92fe-8be93fb3df91"
authors = ["Luca Lorenzini"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
